// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctsxgopaumlioqzkypoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0c3hnb3BhdW1saW9xemt5cG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzMyMjEsImV4cCI6MjA2Nzg0OTIyMX0.glQfzXQk5vmPplXUkY5meKTMtwS5jHduYxtvPBjGXzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});